"use client";

import { useState, useMemo } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowLeft, Copy, Check, Save, RotateCcw, Wand2 } from "lucide-react";
import { fonts } from "@/lib/data/fonts";
import { fontIdToVariable } from "@/lib/fonts";
import { cn } from "@/lib/utils";

type HierarchyLevel = "h1" | "h2" | "h3" | "body" | "caption";

interface TypeSettings {
  fontId: string;
  weight: number;
  size: number;
  lineHeight: number;
  letterSpacing: number;
}

interface CustomHierarchy {
  h1: TypeSettings;
  h2: TypeSettings;
  h3: TypeSettings;
  body: TypeSettings;
  caption: TypeSettings;
}

const defaultHierarchy: CustomHierarchy = {
  h1: { fontId: "playfair-display", weight: 700, size: 48, lineHeight: 1.1, letterSpacing: -0.02 },
  h2: { fontId: "playfair-display", weight: 600, size: 32, lineHeight: 1.2, letterSpacing: -0.01 },
  h3: { fontId: "playfair-display", weight: 600, size: 24, lineHeight: 1.3, letterSpacing: 0 },
  body: { fontId: "inter", weight: 400, size: 16, lineHeight: 1.7, letterSpacing: 0 },
  caption: { fontId: "inter", weight: 400, size: 14, lineHeight: 1.5, letterSpacing: 0 },
};

const levelLabels: Record<HierarchyLevel, string> = {
  h1: "Heading 1",
  h2: "Heading 2",
  h3: "Heading 3",
  body: "Body",
  caption: "Caption",
};

const sampleTexts: Record<HierarchyLevel, string> = {
  h1: "The Art of Typography",
  h2: "Finding the perfect pairing",
  h3: "Balance and harmony in design",
  body: "Great typography is invisible. It seamlessly guides readers through content without calling attention to itself. The best font pairings create visual harmony while maintaining clear hierarchy.",
  caption: "Custom combination • Built with Fontkin",
};

// Organize fonts by category (computed at module level)
const fontsByCategory = (() => {
  const categories: Record<string, typeof fonts> = {};
  fonts.forEach((font) => {
    const category = font.category || "Other";
    if (!categories[category]) {
      categories[category] = [];
    }
    categories[category].push(font);
  });
  return categories;
})();

export default function BuilderPage() {
  const [hierarchy, setHierarchy] = useState<CustomHierarchy>(defaultHierarchy);
  const [comboName, setComboName] = useState("My Custom Combo");
  const [copiedFormat, setCopiedFormat] = useState<string | null>(null);
  const [activeLevel, setActiveLevel] = useState<HierarchyLevel>("h1");

  const updateLevel = (level: HierarchyLevel, updates: Partial<TypeSettings>) => {
    setHierarchy((prev) => ({
      ...prev,
      [level]: { ...prev[level], ...updates },
    }));
  };

  const resetToDefaults = () => {
    setHierarchy(defaultHierarchy);
    setComboName("My Custom Combo");
  };

  const generateCSS = () => {
    const lines = Object.entries(hierarchy).map(([level, settings]) => {
      const font = fonts.find((f) => f.id === settings.fontId);
      return `.${level} {
  font-family: "${font?.name || settings.fontId}", ${font?.classification === "serif" ? "serif" : "sans-serif"};
  font-weight: ${settings.weight};
  font-size: ${settings.size}px;
  line-height: ${settings.lineHeight};${settings.letterSpacing !== 0 ? `\n  letter-spacing: ${settings.letterSpacing}em;` : ""}
}`;
    });
    return `/* ${comboName} - Generated by Fontkin */\n\n${lines.join("\n\n")}`;
  };

  const generateTailwind = () => {
    const config = Object.entries(hierarchy).reduce(
      (acc, [level, settings]) => {
        const font = fonts.find((f) => f.id === settings.fontId);
        acc[level] = {
          fontFamily: font?.name || settings.fontId,
          fontWeight: settings.weight,
          fontSize: `${settings.size}px`,
          lineHeight: settings.lineHeight,
          ...(settings.letterSpacing !== 0 && { letterSpacing: `${settings.letterSpacing}em` }),
        };
        return acc;
      },
      {} as Record<string, object>
    );
    return `// ${comboName} - Generated by Fontkin\n\nconst typography = ${JSON.stringify(config, null, 2)}`;
  };

  const generateAIPrompt = () => {
    const headingFont = fonts.find((f) => f.id === hierarchy.h1.fontId);
    const bodyFont = fonts.find((f) => f.id === hierarchy.body.fontId);
    return `Typography System: "${comboName}"

Heading Font: ${headingFont?.name || hierarchy.h1.fontId}
- Style: ${headingFont?.classification || "unknown"}
- Use for: Headlines, titles, and emphasis

Body Font: ${bodyFont?.name || hierarchy.body.fontId}
- Style: ${bodyFont?.classification || "unknown"}
- Use for: Paragraphs, descriptions, and readable content

Type Scale:
- H1: ${hierarchy.h1.size}px, weight ${hierarchy.h1.weight}
- H2: ${hierarchy.h2.size}px, weight ${hierarchy.h2.weight}
- H3: ${hierarchy.h3.size}px, weight ${hierarchy.h3.weight}
- Body: ${hierarchy.body.size}px, weight ${hierarchy.body.weight}
- Caption: ${hierarchy.caption.size}px, weight ${hierarchy.caption.weight}

Design Guidelines:
- Use consistent line heights for rhythm
- Maintain clear visual hierarchy through size and weight contrast
- Pair ${headingFont?.name || "heading font"}'s ${headingFont?.classification || ""} character with ${bodyFont?.name || "body font"}'s readability`;
  };

  const copyToClipboard = async (text: string, format: string) => {
    await navigator.clipboard.writeText(text);
    setCopiedFormat(format);
    setTimeout(() => setCopiedFormat(null), 2000);
  };

  const currentSettings = hierarchy[activeLevel];
  const currentFont = fonts.find((f) => f.id === currentSettings.fontId);

  return (
    <div className="min-h-screen">
      {/* Header */}
      <div className="border-b">
        <div className="max-w-[1600px] mx-auto px-6 md:px-12 lg:px-20 py-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Link
                href="/explore"
                className="inline-flex items-center gap-2 text-sm text-caption hover:text-foreground transition-colors"
              >
                <ArrowLeft className="h-4 w-4" />
                Back
              </Link>
              <div className="h-4 w-px bg-border" />
              <div className="flex items-center gap-2">
                <Wand2 className="h-5 w-5 text-caption" />
                <h1 className="text-lg font-medium">Custom Combo Builder</h1>
              </div>
            </div>
            <button
              onClick={resetToDefaults}
              className="text-sm text-caption hover:text-foreground transition-colors flex items-center gap-1.5"
            >
              <RotateCcw className="h-4 w-4" />
              Reset
            </button>
          </div>
        </div>
      </div>

      <div className="max-w-[1600px] mx-auto px-6 md:px-12 lg:px-20 py-8">
        <div className="grid lg:grid-cols-2 gap-8">
          {/* Controls Panel */}
          <div className="space-y-6">
            {/* Combo Name */}
            <div className="space-y-2">
              <label className="text-sm font-medium text-body">Combo Name</label>
              <input
                type="text"
                value={comboName}
                onChange={(e) => setComboName(e.target.value)}
                className="w-full px-4 py-2.5 border rounded-lg bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-foreground/20"
                placeholder="My Custom Combo"
              />
            </div>

            {/* Level Tabs */}
            <div className="border rounded-lg overflow-hidden">
              <div className="flex border-b bg-muted/30">
                {(Object.keys(levelLabels) as HierarchyLevel[]).map((level) => (
                  <button
                    key={level}
                    onClick={() => setActiveLevel(level)}
                    className={cn(
                      "flex-1 px-4 py-3 text-sm font-medium transition-colors",
                      activeLevel === level
                        ? "bg-background text-foreground"
                        : "text-caption hover:text-foreground"
                    )}
                  >
                    {level.toUpperCase()}
                  </button>
                ))}
              </div>

              {/* Level Settings */}
              <div className="p-6 space-y-5">
                <h3 className="text-sm font-medium">{levelLabels[activeLevel]} Settings</h3>

                {/* Font Selection */}
                <div className="space-y-2">
                  <label className="text-xs text-caption uppercase tracking-wide">Font Family</label>
                  <select
                    value={currentSettings.fontId}
                    onChange={(e) => updateLevel(activeLevel, { fontId: e.target.value })}
                    className="w-full px-3 py-2 border rounded-lg bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-foreground/20"
                  >
                    {Object.entries(fontsByCategory).map(([category, categoryFonts]) => (
                      <optgroup key={category} label={category}>
                        {categoryFonts.map((font) => (
                          <option key={font.id} value={font.id}>
                            {font.name}
                          </option>
                        ))}
                      </optgroup>
                    ))}
                  </select>
                </div>

                {/* Weight Slider */}
                <div className="space-y-2">
                  <div className="flex justify-between">
                    <label className="text-xs text-caption uppercase tracking-wide">Weight</label>
                    <span className="text-xs font-mono text-body">{currentSettings.weight}</span>
                  </div>
                  <input
                    type="range"
                    min="100"
                    max="900"
                    step="100"
                    value={currentSettings.weight}
                    onChange={(e) => updateLevel(activeLevel, { weight: parseInt(e.target.value) })}
                    className="w-full accent-foreground"
                  />
                </div>

                {/* Size Slider */}
                <div className="space-y-2">
                  <div className="flex justify-between">
                    <label className="text-xs text-caption uppercase tracking-wide">Size</label>
                    <span className="text-xs font-mono text-body">{currentSettings.size}px</span>
                  </div>
                  <input
                    type="range"
                    min="10"
                    max="96"
                    step="1"
                    value={currentSettings.size}
                    onChange={(e) => updateLevel(activeLevel, { size: parseInt(e.target.value) })}
                    className="w-full accent-foreground"
                  />
                </div>

                {/* Line Height Slider */}
                <div className="space-y-2">
                  <div className="flex justify-between">
                    <label className="text-xs text-caption uppercase tracking-wide">Line Height</label>
                    <span className="text-xs font-mono text-body">{currentSettings.lineHeight}</span>
                  </div>
                  <input
                    type="range"
                    min="0.8"
                    max="2.5"
                    step="0.05"
                    value={currentSettings.lineHeight}
                    onChange={(e) => updateLevel(activeLevel, { lineHeight: parseFloat(e.target.value) })}
                    className="w-full accent-foreground"
                  />
                </div>

                {/* Letter Spacing Slider */}
                <div className="space-y-2">
                  <div className="flex justify-between">
                    <label className="text-xs text-caption uppercase tracking-wide">Letter Spacing</label>
                    <span className="text-xs font-mono text-body">{currentSettings.letterSpacing}em</span>
                  </div>
                  <input
                    type="range"
                    min="-0.05"
                    max="0.1"
                    step="0.005"
                    value={currentSettings.letterSpacing}
                    onChange={(e) => updateLevel(activeLevel, { letterSpacing: parseFloat(e.target.value) })}
                    className="w-full accent-foreground"
                  />
                </div>
              </div>
            </div>

            {/* Export Buttons */}
            <div className="space-y-3">
              <h3 className="text-sm font-medium">Export</h3>
              <div className="grid grid-cols-3 gap-3">
                <button
                  onClick={() => copyToClipboard(generateCSS(), "css")}
                  className="flex items-center justify-center gap-2 px-4 py-2.5 border rounded-lg text-sm hover:bg-muted/50 transition-colors"
                >
                  {copiedFormat === "css" ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                  CSS
                </button>
                <button
                  onClick={() => copyToClipboard(generateTailwind(), "tailwind")}
                  className="flex items-center justify-center gap-2 px-4 py-2.5 border rounded-lg text-sm hover:bg-muted/50 transition-colors"
                >
                  {copiedFormat === "tailwind" ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                  Tailwind
                </button>
                <button
                  onClick={() => copyToClipboard(generateAIPrompt(), "ai")}
                  className="flex items-center justify-center gap-2 px-4 py-2.5 border rounded-lg text-sm hover:bg-muted/50 transition-colors"
                >
                  {copiedFormat === "ai" ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                  AI Prompt
                </button>
              </div>
            </div>
          </div>

          {/* Live Preview Panel */}
          <div className="lg:sticky lg:top-24 h-fit">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="border rounded-xl overflow-hidden bg-card"
            >
              <div className="px-6 py-4 border-b bg-muted/30">
                <h2 className="text-sm font-medium">Live Preview</h2>
                <p className="text-xs text-caption mt-0.5">{comboName}</p>
              </div>

              <div className="p-8 space-y-6">
                {(Object.keys(hierarchy) as HierarchyLevel[]).map((level) => {
                  const settings = hierarchy[level];
                  const font = fonts.find((f) => f.id === settings.fontId);
                  const fontFamily = fontIdToVariable[settings.fontId] || `"${font?.name}", sans-serif`;

                  return (
                    <motion.div
                      key={level}
                      initial={false}
                      animate={{
                        opacity: activeLevel === level ? 1 : 0.5,
                        scale: activeLevel === level ? 1 : 0.98,
                      }}
                      className={cn(
                        "transition-all cursor-pointer rounded-lg p-3 -mx-3",
                        activeLevel === level ? "bg-muted/30" : "hover:bg-muted/20"
                      )}
                      onClick={() => setActiveLevel(level)}
                    >
                      <p
                        style={{
                          fontFamily,
                          fontWeight: settings.weight,
                          fontSize: `${settings.size}px`,
                          lineHeight: settings.lineHeight,
                          letterSpacing: `${settings.letterSpacing}em`,
                        }}
                        className={cn(
                          level === "body" && "text-body",
                          level === "caption" && "text-caption"
                        )}
                      >
                        {sampleTexts[level]}
                      </p>
                      <p className="text-[10px] text-caption mt-2 font-mono">
                        {level.toUpperCase()} • {font?.name} {settings.weight} • {settings.size}px
                      </p>
                    </motion.div>
                  );
                })}
              </div>
            </motion.div>

            {/* Quick Info */}
            <div className="mt-4 p-4 bg-muted/30 rounded-lg">
              <h3 className="text-xs font-medium mb-2">Fonts Used</h3>
              <div className="flex flex-wrap gap-2">
                {Array.from(new Set(Object.values(hierarchy).map((s) => s.fontId))).map((fontId) => {
                  const font = fonts.find((f) => f.id === fontId);
                  return (
                    <span
                      key={fontId}
                      className="text-xs px-2 py-1 bg-foreground/5 rounded-full text-body"
                    >
                      {font?.name || fontId}
                    </span>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
